version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: apscheduler_db
    environment:
      POSTGRES_USER: scheduler
      POSTGRES_PASSWORD: scheduler_pass
      POSTGRES_DB: scheduler_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
